# Generated by Django 3.2.7 on 2022-01-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('detail_name', models.CharField(max_length=255)),
                ('detail_mark', models.CharField(max_length=255)),
                ('eskd_mark', models.CharField(blank=True, max_length=255)),
                ('standard_name', models.CharField(max_length=255)),
                ('standard_mark', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('depth', models.CharField(max_length=255)),
                ('cost_result_without_cover', models.CharField(max_length=255)),
                ('cost_result_in_cover', models.CharField(max_length=255)),
                ('type_of_execution', models.CharField(max_length=255)),
            ],
        ),
    ]
